{% set version = "1.7.2" %}

package:
  name: highspy
  version: {{ version }}

source:
  url: https://github.com/ERGO-Code/HiGHS/archive/v{{ version }}.tar.gz
  sha256: 5ff96c14ae19592d3568e9ae107624cbaf3409d328fb1a586359f0adf9b34bf7
  patches:
    - patches/0001-Got-error-about-missing-std-tolower-on-MSVC.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  ignore_run_exports:
    - numpy

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
    - scikit-build-core
    - numpy
    - pybind11
  run:
    - python
    - numpy

test:
  files:
    - tests
  imports:
    - highspy
  commands:
    - python -m unittest tests/test_highspy.py
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: 'High performance serial and parallel solver for large scale sparse linear optimization problems'
  description: |
    HiGHS is a high performance serial and parallel solver for large scale
    sparse linear optimization problems of the form

         min ½ xᵀ Q x + cᵀ x     s.t. L ≤ Ax ≤ U; l ≤ x ≤ u

    where Q must be positive semi-definite and, if Q is zero, there may be a
    requirement that some of the variables take integer values. Thus HiGHS can
    solve linear programming (LP) problems, convex quadratic programming (QP)
    problems, and mixed integer programming (MIP) problems. It is mainly written in
    C++, but also has some C. It has been developed and tested on various Linux,
    MacOS and Windows installations.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://ergo-code.github.io/HiGHS/stable/
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - adament
